#!C:\xampp\php\php.exe
<?php
if(php_sapi_name()!=="cli"){
    echo "This is allowed to run only from console ,BYE!!";
    exit;

}


require __DIR__ ."/vendor/autoload.php";

use Minicli\App;
use Minicli\CommandCall;

$app =new App();
$app->setSignature("usage: minicli hello name [ user=name ]");

$app->registerCommand("help",function(CommandCall $call)use ($app){
    $app->printSignature();
    print_r($call->params);
});

/*$app->registerCommand("hello",function(array $argv)use ($app){
    $name=isset($argv[2])?$argv[2] : "World";
    $app->getPrinter()->display("Hello $name !!");
});*/
//$app->registerController("hello",new \App\Command\HelloController($app));
$app->runCommand($argv);